config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users
  root to: 'pages#home'

  get "pages/download_pdf"


  namespace :admin do
    get '', action: 'index', as: '/'
    resources :projects, except: :show
    resources :skills, except: :show
  end

  resources :projects, only: :show

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_rich_text :description
  has_rich_text :collaborator_desc
  has_many :project_skills, dependent: :destroy
  has_many :skills, through: :project_skills

  validates :title, :date_start, presence: true

  has_many_attached :photos
end

app/models/project_skill.rb
class ProjectSkill < ApplicationRecord
  belongs_to :project
  belongs_to :skill
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :project_skills
  has_many :projects, through: :project_skills

  has_one_attached :photo

  validates :title, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: (1..3) }

  enum specialty: { Design: "0", Web: "1"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < AdminController
    require 'action_view'
    include ActionView::Helpers::DateHelper

    before_action :set_project, only: [:edit, :update, :destroy]

    def index
      @projects = Project.order(created_at: :desc)
    end

    def new
      @project = Project.new
    end

    def create
      @project = Project.new(project_params)
      if @project.save
        flash.notice = "Projet ajouté"
        redirect_to root_path(anchor: "projects")
      else
        flash.alert = "Une erreur est survenue"
        render :new
      end
    end

    def edit
    end

    def update
      @project.update(project_params)
      redirect_to project_path(@project)
    end

    def destroy
      @project.destroy
      redirect_to admin_path
    end

    def time_ago(date)
      from_time = Time.now
      distance_of_time_in_words(from_time, date)
    end
    helper_method :time_ago

    private

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :description, :finished, :date_start, :date_end, :url, :collaborator_desc, photos: [], skill_ids: [])
    end
  end
end

app/controllers/admin/skills_controller.rb
module Admin
  class SkillsController < AdminController
    before_action :set_skill, only: %i[edit update destroy]

    def index
      @skills = Skill.includes(:projects).all.order(:id)
    end

    def new
      @skill = Skill.new
    end

    def create
      @skill = Skill.new(skill_params)

      if @skill.save
        flash.notice = "Compétence ajoutée"
        redirect_to admin_skills_path
      else
        flash.alert = "Une erreur est survenue"
        render :new
      end
    end

    def edit
    end

    def update
      if @skill.update(skill_params)
        flash.notice = "Modifications enregistrées"
        redirect_to admin_skills_path
      else
        flash.alert = "Une erreur est survenue"
        render :edit
      end
    end

    def destroy
      @skill.destroy
      redirect_to admin_projects_path
    end

    private

    def set_skill
      @skill = Skill.find(params[:id])
    end

    def skill_params
      params.require(:skill).permit(:title, :rating, :specialty, :photo)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!

  def index
    @projects = Project.includes(:skills).order(updated_at: :desc)
    @skills = Skill.includes(:projects).order(created_at: :desc)
    @finished_projects = Project.where(finished: true).count
    @expert_skills = Skill.where(rating: 3).count
  end

  def authenticate_admin!
    authenticate_user!
    redirect_to :home unless current_user.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # skip_before_action :authenticate_user!, only: :home

  def home
  end

  # include Pundit

  # # Pundit: white-list approach.
  # after_action :verify_authorized, except: :home, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :home, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "Vous n'êtes pas autorisé à effectuer cette action."
    redirect_to(root_path)
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    # @skills_design = Skill.where("specialty = ? AND rating = ?", "0", 3).limit(2)
    @skill_adobe_xd = Skill.where("title = ?", "Adobe XD").first
    @skill_figma = Skill.where("title = ?", "Figma").first

    @skills_rails = Skill.where("title = ?", "Rails").first
    @skills_web_standard = Skill.where("specialty = ? AND rating = ?", "1", 2).first
    @skills_js = Skill.where("title = ?", "Javascript").first

    @projects = Project.order(updated_at: :desc)
    @map = Project.where('id = ?', 1).first

    @behance = [
      {
        url: "https://res.cloudinary.com/dskz4h4td/image/upload/v1670352942/mockup_en2clik_1700_t29i6w.jpg",
        title: "En2clik"
      },
      {
        url: "https://res.cloudinary.com/dskz4h4td/image/upload/v1670353369/mockups_insta_jyrjsw.jpg",
        title: "Martinique Transport"
      },
      {
        url: "https://res.cloudinary.com/dskz4h4td/image/upload/v1670353494/dp_mockup_1700_hs4ui2.jpg",
        title: "Club Ti Chimen"
      }
    ]
  end

  def download_pdf
    send_file(
      "#{Rails.root}/app/assets/cv_hardy_dessources_laura_Fullstack_Developper.pdf",
      filename: "cv_Hardy_Dessources_Laura_Fullstack_developper.pdf",
      type: "application/pdf"
    )
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # skip_after_action :verify_authorized, only: :show
  def show
    @project = Project.find(params[:id])
    unless @project.date_end === nil
      @nb_jours = (@project.date_end - @project.date_start).
    to_i
    end
  end

  def date_format(date)
    date.strftime("%-d/%-m/%Y")
  end

  helper_method :date_format
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/index.html.erb
<div class="header">
  <div class="container-fluid">
    <div class="header-body">
      <h6 class="header-pretitle">
        Dashboard
      </h6>

      <h1 class="header-title">
        Tableau de bord
      </h1>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12 col-lg-6 col-xl-3">

      <!-- Time -->
      <div class="card border-secondary">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col">

              <!-- Title -->
              <h6 class="text-uppercase text-secondary mb-2">
                Nombre de projets
              </h6>

              <!-- Heading -->
              <span class="h2 mb-0">
                <%= pluralize Project.count, "projet" %>
              </span>

            </div>
            <div class="col-auto">

              <!-- Icone -->
              <span class="h2 fe fe-file text-secondary mb-0"></span>

            </div>
          </div> <!-- / .row -->
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-6 col-xl-3">

      <!-- Hours -->
      <div class="card">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col">

              <!-- Title -->
              <h6 class="text-uppercase text-muted mb-2">
                Nbr total de projets finis
              </h6>

              <!-- Heading -->
              <span class="h2 mb-0">
                <%= pluralize @finished_projects, "projet fini" %>
              </span>

            </div>
            <div class="col-auto">

              <!-- Icone -->
              <span class="h2 fe fe-calendar text-muted mb-0"></span>

            </div>
          </div> <!-- / .row -->
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-6 col-xl-3">

      <!-- Value  -->
      <div class="card">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col">

              <!-- Title -->
              <h6 class="text-uppercase text-muted mb-2">
                Nombre de compétences
              </h6>

              <!-- Heading -->
              <span class="h2 mb-0">
                <%= Skill.count %> compétences
              </span>
            </div>
            <div class="col-auto">

              <!-- Icone -->
              <span class="h2 fe fe-map text-muted mb-0"></span>

            </div>
          </div> <!-- / .row -->
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-6 col-xl-3">

      <!-- Exit -->
      <div class="card">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col">

              <!-- Title -->
              <h6 class="text-uppercase text-muted mb-2">
                Nombre de compétences niveau "Expert"
              </h6>

              <!-- Heading -->
              <span class="h2 mb-0">
                <%= pluralize @expert_skills, "compétence" %>
              </span>

            </div>
            <div class="col-auto">

              <!-- Icone -->
              <span class="h2 fe fe-users text-muted mb-0"></span>

            </div>
          </div> <!-- / .row -->
        </div>
      </div>
    </div>

  </div>

  <hr class="mb-5">

  <%# Projets %>
  <div class="row">
    <div class="card">
      <div class="card-header">
        <!-- Title -->
        <h2 class="card-header-title">
          Projets
        </h2>
      </div>
      <div class="table-responsive mb-0">
        <table class="table table-sm table-nowrap card-table table-hover">
          <thead>
            <tr>
              <th>
                <a href="#" class="text-muted list-sort" data-sort="project-project">
                  Projet
                </a>
              </th>
              <th>
                <a href="#" class="text-muted list-sort" data-sort="project-status">
                  Status
                </a>
              </th>
              <th>
                <a href="#" class="text-muted list-sort" data-sort="project-date">
                  Date de début
                </a>
              </th>
              <th>
                <a href="#" class="text-muted list-sort">
                  Compétences associées
                </a>
              </th>
              <th></th>
            </tr>
          </thead>

          <%###################
          ITERATE OVER PROJECTS
          ####################
          %>

          <% @projects.each do |project| %>

          <tbody class="list">
            <tr>
              <td class="project-project">

                <!-- Heading -->
                <h4 class="fw-normal mb-1"><%= project.title %></h4>

                <!-- Text  -->
                <small class="text-muted"><%= project.collaborator_desc %></small>

              </td>
              <td class="project-status">

                <!-- Badge -->
                <% if project.finished %>
                  <span class="badge bg-success-soft">Terminé</span>
                <% else %>
                  <span class="badge bg-danger-soft">En cours</span>
                <% end %>

              </td>
              <td class="project-date">

                <!-- Time -->
                <time><%= project.date_start.strftime("%d/%m/%Y") %></time>

              </td>
              <td class="text-end">
              <% project.skills.each do |skill| %>
                <div class="tag-skills d-flex">
                  <span>#<%= skill.title %></span>
                </div>
              <% end %>
              </td>
              <td class="text-end">

                <!-- Dropdown -->
                <div class="dropdown">
                  <a href="#" class="dropdown-ellipses dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fe fe-more-vertical"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">
                    <%= link_to "Modifier", edit_admin_project_path(project), class: "dropdown-item" %>
                    <%= link_to "Supprimer", admin_project_path(project), method: :delete,  data: { confirm: "Êtes-vous sûr ? Cette action supprimera définitivement ce projet." }, class: "dropdown-item" %>
                  </div>
                </div>

              </td>
            </tr>
          </tbody>

          <% end %>
        </table>
      </div>
    </div>
  </div>

  <%# Skills %>
  <div class="row">
    <div class="card">
      <div class="card-header">
        <!-- Title -->
        <h2 class="card-header-title">
          Compétences
        </h2>
      </div>
      <div class="table-responsive mb-0">
        <table class="table table-sm table-nowrap card-table table-hover">
          <thead>
            <tr>
              <th>
                <a href="#" class="text-muted list-sort" data-sort="project-project">
                  Compétence
                </a>
              </th>
              <th>
                <a href="#" class="text-muted list-sort" data-sort="project-status">
                  Niveau
                </a>
              </th>
              <th>
                <a href="#" class="text-muted list-sort">
                  Domaine
                </a>
              </th>
              <th>
                <a href="#" class="text-muted list-sort">
                  Projets associés
                </a>
              </th>
              <th></th>
            </tr>
          </thead>

          <%###################
          ITERATE OVER SKILLS
          ####################
          %>

          <% @skills.each do |skill| %>

          <tbody class="list">
            <tr>
              <td class="project-project">
              <div class="col-auto d-flex align-items-center">

                <!-- Avatar -->
                <figure class="m-0 avatar">
                <% if skill.photo.attached? %>
                  <%= cl_image_tag skill.photo.key, class: "avatar-img rounded", alt: "icon de compétence" %>
                <% else %>
                  <%= image_tag "skill_icon.svg", class: "avatar-img rounded", alt: "icon de compétence"  %>
                <% end %>
                </figure>

                  <!-- Heading -->
                  <h4 class="fw-normal mb-0 ms-3"><%= skill.title %></h4>
              </div>
              </td>
              <td class="project-status">
                  <!-- Niveaux -->
                  <div class="skill-levels">
                    <%= render 'admin/partials/skill_levels', skill: skill %>
                  </div>
                </div>
              </td>
              <!-- Spécialty -->
              <td>
                <div>
                  <span><%= skill.specialty %></span>
                </div>
              </td>
              <td class="text-end">
              <% skill.projects.each do |project| %>
                <div class="tag-skills d-flex">
                  <span>#<%= project.title %></span>
                </div>
              <% end %>
              </td>
              <td class="text-end">

                <!-- Dropdown -->
                <div class="dropdown">
                  <a href="#" class="dropdown-ellipses dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fe fe-more-vertical"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">
                    <%= link_to "Modifier", edit_admin_skill_path(skill), class: "dropdown-item" %>
                    <%= link_to "Supprimer", admin_skill_path(skill), method: :delete,  data: { confirm: "Êtes-vous sûr ? Cette action supprimera définitivement ce projet." }, class: "dropdown-item" %>
                  </div>
                </div>

              </td>
            </tr>
          </tbody>

          <% end %>
        </table>
      </div>
    </div>
  </div>

</div>

app/views/admin/partials/_skill_levels.html.erb
<% if skill.rating == 1 %>
  <span class="active"></span>
  <span></span>
  <span></span>
<% elsif skill.rating == 2%>
  <span class="active"></span>
  <span class="active"></span>
  <span></span>
<% else %>
  <span class="active"></span>
  <span class="active"></span>
  <span class="active"></span>
<% end %>

app/views/admin/projects/index.html.erb
<div class="container-fluid">
  <h1 class="mt-4"><%= pluralize @projects.size, "projet" %></h1>
  <!-- Tab content -->
  <div class="tab-content">
    <div class="tab-pane fade active show" id="tabPaneOne" role="tabpanel">
      <div class="row listAlias">
      <% @projects.each do |project| %>

        <div class="col-12 col-md-6 col-xl-4">

          <!-- Card -->
          <div class="card">

            <!-- Image -->
            <%= link_to project_path(project) do %>
            <figure>
              <%= cl_image_tag project.photos[0].key, class: "card-img-top"  %>
            </figure>
            <% end %>

            <!-- Body -->
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col">

                  <!-- Title -->
                  <h4 class="mb-2 name">
                    <%= link_to project_path(project) do %>
                      <%= project.title %>
                    <% end %>
                  </h4>

                  <!-- Subtitle -->
                  <p class="card-text small text-muted">
                    Updated <%= time_ago(project.updated_at) %>
                  </p>

                </div>
                <div class="col-auto">

                  <!-- Dropdown -->
                  <div class="dropdown">
                    <a href="#" class="dropdown-ellipses dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fe fe-more-vertical"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                      <%= link_to "Modifier", edit_admin_project_path(project), class: "dropdown-item" %>
                      <%= link_to "Supprimer", admin_project_path(project), method: :delete,  data: { confirm: "Êtes-vous sûr ? Cette action supprimera définitivement ce projet." }, class: "dropdown-item" %>
                    </div>
                  </div>

                </div>
              </div> <!-- / .row -->
            </div>

            <!-- Footer -->
            <div class="card-footer card-footer-boxed">
              <div class="row align-items-center">
                <div class="col">
                  <div class="row align-items-center g-0">
                    <div class="col-auto">

                      <!-- Value -->
                      <% if project.finished %>
                      <div class="small me-2">100%</div>
                      <% else %>
                      <div class="small me-2">0%</div>
                      <% end %>

                    </div>
                    <div class="col">

                      <!-- Progress -->
                      <div class="progress progress-sm">
                      <% if project.finished %>
                         <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                      <% else %>
                         <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                      <% end %>
                      </div>

                    </div>
                  </div> <!-- / .row -->
                </div>
              </div> <!-- / .row -->
            </div>
          </div>

        </div>
      <% end %>
      </div> <!-- / .row -->
    </div>
  </div> <!-- / .tab-content -->
</div>

app/views/admin/skills/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10 col-xl-8">

      <!-- Header -->
      <div class="header mt-md-5">
        <div class="header-body">
          <div class="row align-items-center">
            <div class="col">

              <!-- Pretitle -->
              <h6 class="header-pretitle">
                Modification compétence
              </h6>

              <!-- Title -->
              <h1 class="header-title">
                Modifier <%= @skill.title %>
              </h1>

            </div>
          </div> <!-- / .row -->
        </div>
      </div>

      <!-- Form -->
      <%= simple_form_for(@skill, url: admin_skill_path, :method => :patch, html: { class: "mb-4"}) do |f| %>

        <!-- Skill name -->
        <div class="form-group">
          <!-- Input -->
          <%= f.input :title, label: "Nom de la compétence", label_html: { class: "form-label" }, input_html: { class: "form-control" } %>
        </div>

        <!-- Skill rating -->
        <div class="form-group">
          <!-- Input -->
          <%= f.input :rating, collection: 1..3, label: "Niveau de la compétence", label_html: { class: "form-label" }, input_html: { class: "form-control" } %>
        </div>

        <!-- Skill specialty -->
        <div class="form-group">
          <!-- Input -->
          <%= f.input :specialty, collection: [['Design', '0'], ['Web', '1']], label: "Domaine de compétence", label_html: { class: "form-label" }, input_html: { class: "form-control" } %>
        </div>

        <!-- Divider -->
        <hr class="mt-5 mb-5">

        <!-- Skill image -->
        <div class="form-group">
          <!-- Dropzone -->
          <div class="dropzone dropzone-single mb-3" data-dropzone='{"url": "https://", "maxFiles": 1, "acceptedFiles": "image/*"}'>

            <!-- Fallback -->
            <div class="fallback">
              <div class="form-group">
                <%= f.input :photo, as: :file, label: "Icon compétence", label_html: { class: "form-label" } %>
              </div>
            </div>
          </div>
        </div>

        <!-- Divider -->
        <hr class="mt-5 mb-5">

        <!-- Buttons -->

        <%= f.submit class: "btn w-100 btn-primary" %>
        <%= link_to "Annuler", admin_skills_path, class:"btn w-100 btn-link text-muted mt-2" %>
      <% end %>

    </div>
  </div> <!-- / .row -->
</div>

app/views/admin/skills/index.html.erb
<div class="container-fluid">
  <h1 class="mt-4"><%= pluralize @skills.size, "compétence" %></h1>
  <div class="row">
    <% @skills.each do |skill| %>
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col-auto">

              <!-- Avatar -->
              <figure class="skill-icons">
              <% if skill.photo.attached? %>
                <%= cl_image_tag skill.photo.key, class: "avatar-img rounded", alt: "icon de compétence" %>
              <% else %>
                <%= image_tag "skill_icon.svg", class: "avatar-img rounded", alt: "icon de compétence"  %>
              <% end %>
              </figure>

            </div>
            <div class="col ms-n2">

              <!-- Title -->
              <h4 class="mb-1">
                <%= skill.title %>
              </h4>

              <!-- Progress -->
              <div class="row align-items-center g-0">
                <div class="col">
                  <!-- Progress -->
                  <div class="skill-levels">
                    <%= render 'admin/partials/skill_levels', skill: skill %>
                  </div>

                </div>
              </div> <!-- / .row -->

              <p class="mt-1 mb-0">#<%= skill.specialty %></p>
            </div>

            <div class="col-auto">

              <!-- Dropdown -->
              <div class="dropdown">
                <a href="#" class="dropdown-ellipses dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fe fe-more-vertical"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                  <%= link_to "Modifier", edit_admin_skill_path(skill), class: "dropdown-item" %>
                  <%= link_to "Supprimer", admin_skill_path(skill), method: :delete,  data: { confirm: "Êtes-vous sûr ? Cette action supprimera définitivement cette compétence." }, class: "dropdown-item" %>
                </div>
              </div>

            </div>
          </div> <!-- / .row -->
        </div> <!-- / .card-body -->
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/partials/_admin-sidebar-nav.html.erb
<nav class="navbar navbar-vertical fixed-start navbar-expand-md navbar-dark" id="sidebar">
  <div class="container-fluid">

    <!-- Toggler -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarCollapse" aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Brand -->
    <div class="py-4 d-flex justify-content-center">
      <%= link_to root_path do %>
      <%# <i class="fe fe-home"></i> Accueil %>
        <%= image_tag("logo_white.svg", height:"80", alt: "Accueil") %>
      <% end %>
    </div>

    <!-- User (xs) -->
    <div class="navbar-user d-md-none">

      <!-- Dropdown -->
      <div class="dropdown">

        <!-- Toggle -->
        <a href="#" id="sidebarIcon" class="dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="avatar avatar-sm avatar-online">
            <%= image_tag "laura_avatar.svg", class: " rounded-circle", alt: "user avatar" %>
          </div>
        </a>

        <!-- Menu -->
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="sidebarIcon">
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>

      </div>

    </div>

    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="sidebarCollapse">

      <!-- Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to admin_path, :class=>"nav-link" do %>
            <i class="fe fe-grid"></i> Dashboard
          <% end %>
        </li>
      </ul>

      <!-- Heading -->
      <h6 class="navbar-heading mt-4">
        Projets
      </h6>

      <!-- Navigation -->
     <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to admin_projects_path, :class=>"nav-link" do %>
            <i class="fe fe-file"></i> Mes projets
          <% end %>
        </li>
        <li class="nav-item">
         <%= link_to new_admin_project_path, :class=>"nav-link" do %>
            <i class="fe fe-plus-circle"></i> Créer un projet
          <% end %>
        </li>
      </ul>

      <!-- Heading -->
      <h6 class="navbar-heading mt-4">
        Compétences
      </h6>

      <!-- Navigation -->
     <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to admin_skills_path, :class=>"nav-link" do %>
            <i class="fe fe-file"></i> Mes compétences
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_admin_skill_path, :class=>"nav-link" do %>
            <i class="fe fe-plus-circle"></i> Ajouter une compétence
          <% end %>
        </li>
      </ul>

      <!-- Push content down -->
      <div class="mt-auto"></div>

        <!-- User (md) -->
        <div class="navbar-user d-none d-md-flex" id="sidebarUser">


          <!-- Dropup -->
          <div class="dropup">

            <!-- Toggle -->
            <a href="#" id="sidebarIconCopy" class="dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="avatar avatar-sm avatar-online">
                <%# <img src="{{webRoot}}/assets/img/avatars/profiles/avatar-1.jpg" class="avatar-img rounded-circle" alt="..."> %>
                <%= image_tag "laura_avatar.svg", class: " rounded-circle", alt: "user avatar" %>
              </div>
            </a>

            <!-- Menu -->
            <div class="dropdown-menu" aria-labelledby="sidebarIconCopy">
              <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>

          </div>


        </div>

    </div> <!-- / .navbar-collapse -->

  </div>
</nav>

app/views/layouts/partials/_dl-cv.html.erb
<div class='dl-cv'>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p>En savoir plus sur mon parcours professionnel</p>
        <%= link_to 'Télécharger mon CV', pages_download_pdf_url, target: "_blank", class: 'btn-normal' %>
      </div>
    </div>
  </div>
</div>